name: Test Algorithms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download a9a
      run: |
        mkdir -p data/LibSVM
        wget https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a -O data/LibSVM/a9a.txt
    - name: UnitTest
      run: |
        ./run_unit_tests.sh
    - name: PyTest
      run: |
        pytest ./tests
    - name: UniversalTest
      run: |
        ./tests/run_universal_tests.py
    
